Fixing HexValidator
> Fatal error: Uncaught InvalidArgumentException: Please make sure bytecode is valid.

I was getting the above error when I was trying to deploy my contract. Even though my bytecode is valid, it was failing the test

I fixed the code to use `ctype_xdigit` instead of regular express test